# Generated by Django 6.0.4 on 2026-05-03 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('view_managerdashboard', 'Can view manager dashboard')],
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
