# Generated by Django 6.0.4 on 2026-05-03 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_extrapermission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='extrapermission',
            options={'default_permissions': (), 'managed': False, 'permissions': [('view_managerdashboard', 'Can view manager dashboard'), ('view_riderdashboard', 'Can view rider dashboard')]},
        ),
    ]
