# Generated by Django 6.0.4 on 2026-05-03 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rideraddress',
            name='zone_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
