# Generated by Django 6.0.4 on 2026-05-04 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0002_alter_rideraddress_zone_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderprofile',
            name='full_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='rider_profiles'),
        ),
    ]
