# Generated by Django 6.0.4 on 2026-05-05 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0003_riderprofile_full_name_riderprofile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderapplication',
            name='area_id',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='riderapplication',
            name='city_id',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='riderapplication',
            name='country_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='riderapplication',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='rider_applications'),
        ),
        migrations.AddField(
            model_name='riderapplication',
            name='phone_number',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='riderapplication',
            name='zone_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='license_number',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='nid_number',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
